#! /bin/sh

# star application
## about bspwm 
sxhkd&
xsetroot -cursor_name left_ptr
## any windows manager need to start
fcitx -d
compton -b
xrandr --output DP1 --right-of HDMI2
feh --bg-scale ~/pictures/apple.jpeg

# bspwm configuration
bspc monitor DP1 -d 1 2 3 4 
bspc monitor HDMI2 -d 5 6 7 8
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc rule -a scratchpad sticky=on locked=on state=floating hidden=on
termite --class scratchpad  -e ~/.local/bin/scratch &
