;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	counsel-M-x
	eval-last-sexp
	evil-append
	evil-force-normal-state
	evil-forward-char
	evil-next-line
	evil-previous-line
	evil-repeat-find-char
	paredit-kill
	))

(setq mc/cmds-to-run-once
      '(
	evil-insert
	evil-normal-state
	evil-shift-right
	))
